// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihefvtgzjrjedoivbjqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloZWZ2dGd6anJqZWRvaXZianFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcxOTQyNDgsImV4cCI6MjEwMjc3MDI0OH0.R-7o5Qp95LuGDvEUpZwaZ8uplAEfQjcpyXm-u4LFTQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});